---


- name: Install dependencies
  package:
    name: "{{ grafana_dependencies }}"
    state: present
  register: _install_dep_packages
  until: _install_dep_packages is succeeded
  retries: 5
  delay: 2

- name: Remove conflicting grafana packages
  package:
    name: grafana-data
    state: absent
  register: _old_grafana_pkgs

- name: Add (disabled) Grafana repository file [RHEL/CentOS]
  template:
    src: "{{ grafana_yum_repo_template }}"
    dest: "/etc/yum.repos.d/{{ grafana_yum_repo_template | basename | regex_replace('\\.j2$', '') }}"
    force: true
    backup: true
  when: ansible_pkg_mgr in ['yum', 'dnf']

# Work around the fact the grafana repos are flaky: only enable them if actually required
- name: Check whether Grafana is installed
  # Fails with message below if not installed as repo is disabled
  # Otherwise succeeds. No change in either case!
  package:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  check_mode: true
  register: _existing_install
  failed_when:
    - _existing_install.rc != 0
    - "'No package grafana' not in _existing_install.failures[0]"

- name: Install Grafana package
  ansible.builtin.dnf:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
    enablerepo: grafana
  when: "'No package grafana' in _existing_install.get('failures', [''])[0]"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  notify: restart grafana
